baseURL = "https://learningpatterns.me"
languageCode = "en-gb"
title = "Learning Patterns"
theme = "ananke"
draft = false

[params]
  favicon = ""
  twitter = "https://twitter.com/willfurnass"
  github = "https://github.com/willfurnass"
  gitlab = "https://gitlab.com/willfurnass"

# For Cryogen compatibility
[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"
